const SECRET_WORDS=["JOGOS","FASES","CHEFE","MAGIA","MAPAS","VIDAS","TORRE","ARENA","RUNAS","BOMBA","CHAVE","PORTA","MOEDA","LASER","NAVES","PISTA","DUELO","BARRA","GOLPE","FOICE","RIVAL","MUNDO","NINJA","MIRAS","COMBO","PIXEL","MOUSE","TECLA","CONTA","SENHA","LOGIN","MODOS","TIMES","PONTO","DANOS","ARMAS","CLANS","ELITE","GRANA","GRUPO","HEROI","ITENS","LANCA","LOBBY","MAGOS","NIVEL","PODER","RANKS","SKINS","TURNO","ROUBO","FOGOS","DADOS","PLAYS","FINAL","BOSSF","BESTA","FURIA","CURAR","RAIDE","QUEST","METAS","PILHA","BOTAO","CABOS","TELAS","SONIC","MARIO","ZELDA","KIRBY","METAL","CRASH","FIGHT","KARTS","FARPA","TANKE","SUPOR","MAGOE","LUTAS","ESPIA","FURTO","ALMAS","CRYPT","DRAGO","REINO","REGEN","MINAS"];
const ACCEPTED=new Set(SECRET_WORDS);
const MAX_ROWS=6,WORD_LEN=5;
const state={secret:"",row:0,col:0,board:[],running:false,score:0,finished:false};
const screenStart=document.getElementById("screenStart"),screenGame=document.getElementById("screenGame"),screenOver=document.getElementById("screenOver"),boardEl=document.getElementById("board"),keyboardEl=document.getElementById("keyboard"),scoreDisplay=document.getElementById("scoreDisplay"),roundDisplay=document.getElementById("roundDisplay"),toast=document.getElementById("toast");
function showScreen(n){[screenStart,screenGame,screenOver].forEach(s=>s.classList.add("hidden"));if(n==="start")screenStart.classList.remove("hidden");if(n==="game")screenGame.classList.remove("hidden");if(n==="over")screenOver.classList.remove("hidden")}
function initGame(){state.secret=SECRET_WORDS[Math.floor(Math.random()*SECRET_WORDS.length)];state.row=0;state.col=0;state.board=Array.from({length:MAX_ROWS},()=>Array(WORD_LEN).fill(""));state.score=0;state.running=true;state.finished=false;buildBoard();buildKeyboard();updateHUD();showScreen("game")}
function buildBoard(){boardEl.innerHTML="";for(let r=0;r<MAX_ROWS;r++){const row=document.createElement("div");row.className="board-row";for(let c=0;c<WORD_LEN;c++){const tile=document.createElement("div");tile.className="tile";tile.dataset.row=r;tile.dataset.col=c;row.appendChild(tile)}boardEl.appendChild(row)}}
function buildKeyboard(){const rows=[["Q","W","E","R","T","Y","U","I","O","P"],["A","S","D","F","G","H","J","K","L"],["ENTER","Z","X","C","V","B","N","M","⌫"]];keyboardEl.innerHTML="";rows.forEach(keys=>{const row=document.createElement("div");row.className="key-row";keys.forEach(k=>{const btn=document.createElement("button");btn.className="key";if(k==="ENTER"||k==="⌫")btn.classList.add("wide");btn.textContent=k;btn.dataset.key=k;btn.addEventListener("click",()=>handleKey(k));row.appendChild(btn)});keyboardEl.appendChild(row)})}
function updateHUD(){scoreDisplay.textContent=state.score;roundDisplay.textContent=`${Math.min(state.row+1,MAX_ROWS)}/${MAX_ROWS}`}
function updateTile(r,c){const tile=boardEl.querySelector(`.tile[data-row="${r}"][data-col="${c}"]`);if(!tile)return;tile.textContent=state.board[r][c]||"";tile.classList.toggle("filled",!!state.board[r][c])}
function normalize(k){return String(k).normalize("NFD").replace(/[\u0300-\u036f]/g,"").replace(/Ç/g,"C").replace(/ç/g,"c").toUpperCase().replace(/[^A-Z]/g,"")}
function handleKey(k){if(!state.running||state.finished)return;if(k==="ENTER"){submitGuess();return}if(k==="⌫"||k==="BACKSPACE"){deleteLetter();return}const l=normalize(k);if(/^[A-Z]$/.test(l))addLetter(l)}
function addLetter(l){if(state.col>=WORD_LEN)return;state.board[state.row][state.col]=l;updateTile(state.row,state.col);state.col++}
function deleteLetter(){if(state.col<=0)return;state.col--;state.board[state.row][state.col]="";updateTile(state.row,state.col)}
function submitGuess(){if(state.col<WORD_LEN){showToast("Digite uma palavra com 5 letras.");return}const guess=state.board[state.row].join("");revealGuess(guess);if(guess===state.secret){const points=(MAX_ROWS-state.row)*100;state.score+=points;updateHUD();saveScore(state.score);setTimeout(()=>endGame(true),900);return}state.row++;state.col=0;if(state.row>=MAX_ROWS){setTimeout(()=>endGame(false),900);return}updateHUD()}
function revealGuess(guess){const secret=state.secret.split(""),letters=guess.split(""),result=Array(WORD_LEN).fill("absent");for(let i=0;i<WORD_LEN;i++){if(letters[i]===secret[i]){result[i]="correct";secret[i]=null;letters[i]=null}}for(let i=0;i<WORD_LEN;i++){if(!letters[i])continue;const idx=secret.indexOf(letters[i]);if(idx!==-1){result[i]="present";secret[idx]=null}}result.forEach((status,i)=>{const tile=boardEl.querySelector(`.tile[data-row="${state.row}"][data-col="${i}"]`);setTimeout(()=>{tile.classList.add("reveal",status);updateKeyboardColor(guess[i],status)},i*120)})}
function updateKeyboardColor(letter,status){const key=keyboardEl.querySelector(`.key[data-key="${letter}"]`);if(!key)return;if(key.classList.contains("correct"))return;if(key.classList.contains("present")&&status==="absent")return;key.classList.remove("correct","present","absent");key.classList.add(status)}
function shakeRow(row){const rowEl=boardEl.children[row];if(!rowEl)return;rowEl.animate([{transform:"translateX(0)"},{transform:"translateX(-8px)"},{transform:"translateX(8px)"},{transform:"translateX(-6px)"},{transform:"translateX(6px)"},{transform:"translateX(0)"}],{duration:360,easing:"ease"})}
function endGame(won){state.running=false;state.finished=true;const tries=won?state.row+1:MAX_ROWS;document.getElementById("overIcon").textContent=won?"🏆":"💥";document.getElementById("overTitle").textContent=won?"Você acertou!":"Fim de jogo!";document.getElementById("overText").innerHTML=`A palavra era <strong>${state.secret}</strong>.`;document.getElementById("finalScore").textContent=state.score;document.getElementById("finalTries").textContent=tries;showScreen("over");renderRanking()}
function giveUp(){if(!state.running)return;state.score=0;updateHUD();endGame(false)}
function getRanking(){try{const r=JSON.parse(localStorage.getItem("velora_letreco_ranking"));if(Array.isArray(r))return r}catch(e){}return[{name:"Jogador1",score:500},{name:"Jogador2",score:300},{name:"Jogador3",score:100}]}
function saveScore(score){if(!score)return;let ranking=getRanking(),playerName="Você";try{const u=JSON.parse(localStorage.getItem("velora_user"));if(u)playerName=u.name||"Jogador"}catch(e){}ranking.push({name:playerName,score,date:new Date().toISOString()});ranking.sort((a,b)=>b.score-a.score);ranking=ranking.slice(0,5);localStorage.setItem("velora_letreco_ranking",JSON.stringify(ranking))}
function renderRanking(){const list=document.getElementById("rankingList");if(!list)return;list.innerHTML=getRanking().slice(0,5).map((i,idx)=>`<div class="rank-row"><span>${idx+1}. ${escapeHtml(i.name)}</span><strong>${i.score}</strong></div>`).join("")}
function escapeHtml(t){return String(t).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function showToast(msg){toast.textContent=msg;toast.classList.add("show");setTimeout(()=>toast.classList.remove("show"),2400)}
document.addEventListener("keydown",e=>{if(!state.running)return;if(e.key==="Enter"){e.preventDefault();handleKey("ENTER");return}if(e.key==="Backspace"){e.preventDefault();handleKey("BACKSPACE");return}if(/^[a-zA-Z]$/.test(e.key)){e.preventDefault();handleKey(e.key)}})
document.getElementById("btnStart")?.addEventListener("click",initGame);document.getElementById("btnRestart")?.addEventListener("click",initGame);document.getElementById("btnGiveUp")?.addEventListener("click",giveUp);document.getElementById("btnBackMenu")?.addEventListener("click",()=>{state.running=false;showScreen("start");renderRanking()});
const mobileMenuBtn=document.getElementById("mobileMenuBtn"),mainNav=document.querySelector(".main-nav");mobileMenuBtn?.addEventListener("click",e=>{e.stopPropagation();mainNav?.classList.toggle("active")});document.addEventListener("click",()=>{mainNav?.classList.remove("active")});mainNav?.addEventListener("click",e=>e.stopPropagation());
const userProfile=document.getElementById("userProfile"),userDropdown=document.getElementById("userDropdown"),nameEl=document.getElementById("userName"),initialEl=document.getElementById("userAvatarInitial");try{const u=JSON.parse(localStorage.getItem("velora_user"));if(u&&nameEl)nameEl.textContent=u.name||"Jogador";if(u&&initialEl)initialEl.textContent=(u.name||"J")[0].toUpperCase()}catch(e){}
if(userProfile&&userDropdown){userProfile.addEventListener("click",e=>{e.stopPropagation();userDropdown.classList.toggle("active");userProfile.classList.toggle("active")});document.addEventListener("click",()=>{userDropdown.classList.remove("active");userProfile.classList.remove("active")});userDropdown.addEventListener("click",e=>e.stopPropagation())}
document.getElementById("dropMeuPerfil")?.addEventListener("click",()=>{let u=null;try{u=JSON.parse(localStorage.getItem("velora_user"))}catch(e){}if(!u)window.location.href="../LoginCadastro.html";else if(u.account_type==="developer")window.location.href="../PerfilDev.html";else window.location.href="../PerfilUsuario.html"});
document.getElementById("dropSair")?.addEventListener("click",()=>{localStorage.removeItem("velora_user");window.location.href="../LoginCadastro.html"});document.getElementById("btnFavoritos")?.addEventListener("click",()=>{window.location.href="../ListaFavoritos.html"});
renderRanking();showScreen("start");console.log("🔤 Letreco Game — Velora carregado!");
